PREFIX f1: <http://f1.example.org/>

# Get all drivers and their nationalities
SELECT ?driverName ?nationality
WHERE {
  ?driver a f1:Driver ;
          rdfs:label ?driverName ;
          f1:nationality ?nationality .
}
ORDER BY ?driverName
